name: Build Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Compile discord-bot.java
        run: javac discord-bot.java

      - name: Package to JAR
        run: |
          mkdir -p out
          jar cvfe out/discord-bot.jar DiscordBot discord-bot.class

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: discord-bot
          path: out/discord-bot.jar
