name: Build Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Maven
        run: mvn -B package --file pom.xml

      - name: Build and package JAR
        run: |
          mvn clean compile
          mvn package
          
      - name: Upload JAR artifact
        uses: actions/upload-artifact@4
        with:
          name: discord-bot
          path: target/discord-bot-1.0-SNAPSHOT.jar
